#!/usr/bin/env bash
set -euo pipefail
(
cat <<EOF
package main

// Generated by ./gencapmap.sh, DO NOT MODIFY MANUALLY.

var capabilities = map[string]uintptr{
EOF
sed -n 's/	\(CAP_[^ ]*\) *= \(0x.*\)/	"\1": \2,/p' < vendor/golang.org/x/sys/unix/zerrors_linux.go
echo '}'
) >caps.go
gofmt -w -s caps.go
